version: '3.9'
name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    volumes:
      - ./server/config.ini:/config.ini
    networks:
      - testing_net


  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=1
      - CLI_LOG_LEVEL=DEBUG
      - CLI_FIRSTNAME=Mateo
      - CLI_LASTNAME=Capon Blanquer
      - CLI_DOCUMENT=42496666
      - CLI_BIRTHDATE=2000-03-03
      - CLI_NUMBER=1234
    volumes:
      - ./client/config.yaml:/config.yaml
    networks:
      - testing_net
    depends_on:
      - server

  client2:
    container_name: client2
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=2
      - CLI_LOG_LEVEL=DEBUG
      - CLI_FIRSTNAME=Mateo
      - CLI_LASTNAME=Capon Blanquer
      - CLI_DOCUMENT=42496666
      - CLI_BIRTHDATE=2000-03-03-1
      - CLI_NUMBER=2234
    volumes:
      - ./client/config.yaml:/config.yaml
    networks:
      - testing_net
    depends_on:
      - server

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24

